CREATE OR REPLACE VIEW V_POLICY_POLICY(
	HASH_ROW,
	POLICY_KEY,
	POLICY_REVISION_NUMBER,
	PERSONAL_COMMERCIAL_IND,
	POLICY_STATE,
	JURISDICTION_STATE,
	ADDRESS_KEY,
	BILLING_METHOD,
	DISTRIBUTION_CHANNEL,
	CANCELLED_BY,
	ISSUE_DATE,
	EFFECTIVE_DATE,
	EXPIRATION_DATE,
	BOOK_DATE,
	LOB_KEY,
	AUTOMATED_UNDERWRITING_IND,
	MULTILINE_IND,
	PRIMARY_EXCESS_IND,
	MASTER_POLICY_NUMBER,
	DEC_PAGE_POLICY_NUMBER,
	SOURCE_SYSTEM_POLICYID,
	POLICY_TERM_MASTERID,
	POLICY_GLOBAL_MASTERID,
	SQB_ID,
	NEW_RENEWAL_TYPE,
	NON_RENEWAL_IND,
	PACKAGE_KEY,
	PAYMENT_PLAN,
	POLICY_INCEPTION_IND,
	POLICY_NUMBER,
	POLICY_YEAR,
	POLICY_YEAR_MONTH,
	POLICY_TERM,
	PRIOR_POLICY_NUMBER,
	POLICY_FROM_KEY,
	POLICY_FROM_NUMBER,
	POLICY_FROM_TYPE,
	POLICY_TYPE,
	WRITING_COMPANY_KEY,
	WRITING_COMPANY_DESC,
	ASSUMED_DIRECT_TYPE,
	OCCURENCE_CLAIMS_MADE_TYPE,
	REVISION_EFFECTIVE_DATE,
	REVISION_EXPIRATION_DATE,
	REVISION_ISSUE_DATE,
	SOURCE_SYSTEM_DATE_CREATED,
	SOURCE_SYSTEM_DATE_MODIFIED,
	END_DATE,
	START_DATE,
	STATUS_REASON_KEY,
	STATUS_KEY,
	STATUS_EFFECTIVE_DATE,
	STATUS_ACTIVE_IND,
	TERMINATION_DATE,
	TERMINATION_REASON_KEY,
	TERRITORY_KEY,
	TERRITORY_DESC,
	LATTER_DATE,
	DELETED_IND,
	NON_ADMITTED_IND,
	ADMITTED_TYPE,
	LOAD_DATE,
	DATA_VAR_IND,
	DATA_VAR_IND_DATE,
	ENTITY_TYPE,
	LINEAGEID,
	LINEAGE_ID,
	POLICY_EXTRACT_LOAD_DATE
) as 

with 
CTE_LOAD_DATE  
 AS
 (
 SELECT
 current_timestamp() AS LOAD_DATE
 )   

SELECT   
md5(concat(
	cast(Policy_Key as string),
	cast(POLICY_REVISION_NUMBER as string),
	cast(PERSONAL_COMMERCIAL_IND as string),
	cast(POLICY_STATE as string),
	cast(JURISDICTION_STATE as string),
	cast(ADDRESS_KEY as string),
	cast(BILLING_METHOD as string),
	cast(DISTRIBUTION_CHANNEL as string),
	cast(CANCELLED_BY as string),
	cast(ISSUE_DATE as string),
	cast(EFFECTIVE_DATE as string),
	cast(EXPIRATION_DATE as string),
	cast(BOOK_DATE as string),
	cast(LOB_KEY as string),
	cast(AUTOMATED_UNDERWRITING_IND as string),
	cast(MULTILINE_IND as string),
	cast(PRIMARY_EXCESS_IND as string),
	cast(MASTER_POLICY_NUMBER as string),
	cast(DEC_PAGE_POLICY_NUMBER as string),
	cast(SOURCE_SYSTEM_POLICYID as string),
	cast(POLICY_TERM_MASTERID as string),
	cast(POLICY_GLOBAL_MASTERID as string),
	cast(SQB_ID as string),
	cast(NEW_RENEWAL_TYPE as string),
	cast(NON_RENEWAL_IND as string),
	cast(PACKAGE_KEY as string),
	cast(PAYMENT_PLAN as string),
	cast(POLICY_INCEPTION_IND as string),
	cast(POLICY_NUMBER as string),
	cast(POLICY_YEAR as string),
	cast(POLICY_YEAR_MONTH as string),
	cast(POLICY_TERM as string),
	cast(PRIOR_POLICY_NUMBER as string),
	cast(POLICY_FROM_KEY as string),
	cast(POLICY_FROM_NUMBER as string),
	cast(POLICY_FROM_TYPE as string),
	cast(POLICY_TYPE as string),
	cast(WRITING_COMPANY_KEY as string),
	cast(ASSUMED_DIRECT_TYPE as string),
	cast(OCCURENCE_CLAIMS_MADE_TYPE as string),
	cast(REVISION_EFFECTIVE_DATE as string),
	cast(REVISION_EXPIRATION_DATE as string),
	cast(REVISION_ISSUE_DATE as string),
	cast(STATUS_REASON_KEY as string),
	cast(STATUS_KEY as string),
	cast(STATUS_EFFECTIVE_DATE as string),
	cast(STATUS_ACTIVE_IND as string),
	cast(TERMINATION_REASON_KEY as string),
	cast(TERRITORY_KEY as string),	
	cast(LATTER_DATE as string),
	cast(DELETED_IND as string),
	cast(NON_ADMITTED_IND as string),
	cast(ADMITTED_TYPE as string),
	cast(DATA_VAR_IND as string),
	cast(DATA_VAR_IND_DATE as string)
)) AS HASH_ROW,  
    Policy_Key,  
	POLICY_REVISION_NUMBER, 
	PERSONAL_COMMERCIAL_IND,
	POLICY_STATE,
	JURISDICTION_STATE,
	ADDRESS_KEY, 
	BILLING_METHOD, 
	DISTRIBUTION_CHANNEL , 
	CANCELLED_BY , 
	ISSUE_DATE , 
	EFFECTIVE_DATE , 
	EXPIRATION_DATE , 
	BOOK_DATE , 
	LOB_KEY , 
	AUTOMATED_UNDERWRITING_IND , 
	MULTILINE_IND , 
	PRIMARY_EXCESS_IND , 
	MASTER_POLICY_NUMBER , 
	DEC_PAGE_POLICY_NUMBER , 
	SOURCE_SYSTEM_POLICYID , 
	POLICY_TERM_MASTERID , 
	POLICY_GLOBAL_MASTERID , 
	SQB_ID , 
	CASE WHEN  length(NEW_RENEWAL_TYPE)=0 THEN NULL ELSE  NEW_RENEWAL_TYPE END AS NEW_RENEWAL_TYPE , 
	CASE WHEN STATUS_KEY = 'NONRENEW' THEN 'Y' ELSE NULL END AS NON_RENEWAL_IND , 
	PACKAGE_KEY , 
	PAYMENT_PLAN , 
	POLICY_INCEPTION_IND , 
	POLICY_NUMBER , 
	POLICY_YEAR , 
	POLICY_YEAR_MONTH , 
	POLICY_TERM , 
	PRIOR_POLICY_NUMBER , 
	POLICY_FROM_KEY , 
	POLICY_FROM_NUMBER , 
	POLICY_FROM_TYPE , 
	POLICY_TYPE , 
	WRITING_COMPANY_KEY , 
	WRITING_COMPANY_KEY AS WRITING_COMPANY_DESC,
	ASSUMED_DIRECT_TYPE , 
	OCCURENCE_CLAIMS_MADE_TYPE , 
	REVISION_EFFECTIVE_DATE , 
    REVISION_EXPIRATION_DATE , 
    REVISION_ISSUE_DATE , 
    SOURCE_SYSTEM_DATE_CREATED, 
    SOURCE_SYSTEM_DATE_MODIFIED,
    cast( NULL as timestamp) AS END_DATE,
    START_DATE START_DATE, 
	STATUS_REASON_KEY , 
	STATUS_KEY , 
	STATUS_EFFECTIVE_DATE , 
	STATUS_ACTIVE_IND , 
	TERMINATION_DATE ,
	TERMINATION_REASON_KEY , 
	TERRITORY_KEY , 
	TERRITORY_KEY AS TERRITORY_DESC,
	LATTER_DATE , 
	DELETED_IND , 
	NON_ADMITTED_IND , 
	ADMITTED_TYPE , 
	LOAD_DATE,
	DATA_VAR_IND , 
	DATA_VAR_IND_DATE ,
    'P' AS ENTITY_TYPE,
	LineageId,
	LINEAGE_ID,
    POLICY_EXTRACT_LOAD_DATE
 
FROM (
  SELECT   DISTINCT
	(trim(coalesce(Policy.`Policy.Policy`.PolicyKey, ''))) AS POLICY_KEY,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyNumber, ''))) AS POLICY_REVISION_NUMBER,
	(trim(coalesce(Policy.`Policy.Policy`.PersonalCommercialInd, ''))) AS PERSONAL_COMMERCIAL_IND,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyState, ''))) AS POLICY_STATE,
	(trim(coalesce(Policy.`Policy.Policy`.JurisdictionState, ''))) AS JURISDICTION_STATE,
	(trim(coalesce(Policy.`Policy.Policy`.AddressKey, ''))) AS ADDRESS_KEY,
	(trim(coalesce(cast(null as string), ''))) AS BILLING_METHOD,
	(trim(coalesce(Policy.`Policy.Policy`.DistributionChannel, ''))) AS DISTRIBUTION_CHANNEL,
	(trim(coalesce(cast(null as string), ''))) AS CANCELLED_BY,
    to_timestamp(coalesce(Policy.`Policy.Policy`.IssueDate, '1800-01-01')) AS ISSUE_DATE,
    to_timestamp(coalesce(Policy.`Policy.Policy`.EffectiveDate, '1800-01-01')) AS EFFECTIVE_DATE,
    to_timestamp(coalesce(Policy.`Policy.Policy`.ExpirationDate, '1800-01-01')) AS EXPIRATION_DATE,
    to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS BOOK_DATE, 
	(trim(coalesce(Policy.`Policy.Policy`.LOBKey, ''))) AS LOB_KEY,
	(trim(coalesce(cast(null as string), ''))) AS AUTOMATED_UNDERWRITING_IND,
	(trim(coalesce(Policy.`Policy.Policy`.MultiLineInd, ''))) AS MULTILINE_IND,
	(trim(coalesce(cast(null as string), ''))) AS PRIMARY_EXCESS_IND,
	(trim(coalesce(cast(null as string), ''))) AS MASTER_POLICY_NUMBER,
	(trim(coalesce(cast(null as string), ''))) AS DEC_PAGE_POLICY_NUMBER,
	(trim(coalesce(Policy.`Policy.Policy`.SourceSystemPolicyId, ''))) AS SOURCE_SYSTEM_POLICYID,
	(trim(coalesce(cast(null as string), ''))) AS POLICY_TERM_MASTERID,
	(trim(coalesce(cast(null as string), ''))) AS POLICY_GLOBAL_MASTERID,
	(trim(coalesce(Policy.`Policy.Policy`.SQBID, ''))) AS SQB_ID,
	(trim(coalesce(Policy.`Policy.Policy`.NewRenewalType, ''))) AS NEW_RENEWAL_TYPE,
	(trim(coalesce(cast(null as string), ''))) AS NON_RENEWAL_IND,
	(trim(coalesce(cast(null as string), ''))) AS PACKAGE_KEY,
	(trim(coalesce(cast(null as string), ''))) AS PAYMENT_PLAN,
	(trim(coalesce(cast(null as string), ''))) AS POLICY_INCEPTION_IND,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyNumber, ''))) AS POLICY_NUMBER,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyTerm, ''))) AS POLICY_TERM,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyYear, ''))) AS POLICY_YEAR,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyYearMonth, ''))) AS POLICY_YEAR_MONTH, 
	(trim(coalesce(cast(null as string), ''))) AS PRIOR_POLICY_NUMBER,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyFromKey, ''))) AS POLICY_FROM_KEY,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyFromNumber, ''))) AS POLICY_FROM_NUMBER,
	(trim(coalesce(cast(null as string), ''))) AS POLICY_FROM_TYPE,
	(trim(coalesce(Policy.`Policy.Policy`.PolicyType, ''))) AS POLICY_TYPE,
	(trim(coalesce(Policy.`Policy.Policy`.WritingCompanyKey, ''))) AS WRITING_COMPANY_KEY,
	(trim(coalesce(Policy.`Policy.Policy`.AssumedDirectType, ''))) AS ASSUMED_DIRECT_TYPE,
	(trim(coalesce(cast(null as string), ''))) AS OCCURENCE_CLAIMS_MADE_TYPE,
    to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS REVISION_EFFECTIVE_DATE,
    to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS REVISION_EXPIRATION_DATE,
    to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS REVISION_ISSUE_DATE,
    to_timestamp(coalesce(Policy.`Policy.Policy`.SourceSystemDateCreated, '1800-01-01')) AS SOURCE_SYSTEM_DATE_CREATED,
    to_timestamp(coalesce(Policy.`Policy.Policy`.SourceSystemDateModified, '1800-01-01')) AS SOURCE_SYSTEM_DATE_MODIFIED,
    to_timestamp(coalesce(Policy.`Policy.Policy`.StartDate, '1800-01-01')) AS START_DATE,
	(trim(coalesce(cast(null as string), ''))) AS STATUS_REASON_KEY,
	(trim(coalesce(Policy.`Policy.Policy`.StatusKey, ''))) AS STATUS_KEY,
    to_timestamp(coalesce(Policy.`Policy.Policy`.StatusEffectiveDate, '1800-01-01')) AS STATUS_EFFECTIVE_DATE,
 	(trim(coalesce(cast(null as string), '0'))) AS STATUS_ACTIVE_IND,
	to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS TERMINATION_DATE,
	(trim(coalesce(cast(null as string), ''))) AS TERMINATION_REASON_KEY,
	(trim(coalesce(cast(null as string), ''))) AS TERRITORY_KEY,
    to_timestamp(coalesce(Policy.`Policy.Policy`.LatterDate, '1800-01-01')) AS LATTER_DATE,
	(trim(coalesce(Policy.`Policy.Policy`.`@deleted`, '0'))) AS DELETED_IND,
	(trim(coalesce(cast(null as string), ''))) AS NON_ADMITTED_IND,
	(trim(coalesce(cast(null as string), ''))) AS ADMITTED_TYPE,
  
	(trim(coalesce(cast(null as string), ''))) AS DATA_VAR_IND,
	to_timestamp(coalesce(cast(null as string), '1800-01-01')) AS DATA_VAR_IND_DATE,
    cast(coalesce(Policy.`Policy.Policy`.LineageId, '-99') as bigint) AS LineageId,
	cast(coalesce(Policy.`Policy.Policy`.LineageId, '-99') as bigint) AS LINEAGE_ID,
    to_timestamp(coalesce(Policy.`Policy.Policy`.LoadDate, '1800-01-01')) AS POLICY_EXTRACT_LOAD_DATE

   FROM
	bronze_policy 
    WHERE substring(trim(coalesce(Policy.`Policy.Policy`.PolicyKey, '')), 1, 1) = 'P'
   )
   CROSS JOIN CTE_LOAD_DATE;